/* Crayon Contraptions — generate all 100 levels into js/levels.js.
   node tools/gen.js            build (uses tools/cache for unchanged slots)
   node tools/gen.js --force    rebuild every generated slot
   node tools/gen.js 23 57      rebuild just these level numbers
   Every generated level carries a solution the search proved: it wins, an
   empty sheet does not, and nudged copies mostly still win. */
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { Worker, isMainThread, parentPort, workerData } = require('worker_threads');

const ROOT = path.join(__dirname, '..');
const CACHE = path.join(__dirname, 'cache');
const SRC = ['js/sim.js', 'tools/genlib.js', 'tools/archetypes.js', 'tools/build-level.js'];

if (!isMainThread) {
  const { build } = require('./build-level');
  parentPort.on('message', slot => {
    const t0 = Date.now();
    let res;
    try { res = build(slot, slot.boss ? 30 : 40); } catch (e) { res = { err: { crash: String(e && e.stack || e) } }; }
    parentPort.postMessage({ n: slot.n, res, secs: (Date.now() - t0) / 1000 });
  });
  return;
}

const plan = require('./plan');
const srcHash = crypto.createHash('md5').update(SRC.map(f => fs.readFileSync(path.join(ROOT, f), 'utf8')).join('\n')).digest('hex').slice(0, 10);
const args = process.argv.slice(2), force = args.includes('--force'), only = args.filter(a => /^\d+$/.test(a)).map(Number);
fs.mkdirSync(CACHE, { recursive: true });

const load = require('../test/load');
const HAND = load(['tools/hand.js']).HAND;

const slots = [];
plan.forEach((w, wi) => w.levels.forEach((lv, li) => slots.push(Object.assign({ n: wi * 10 + li + 1, world: wi }, lv))));
const keyOf = s => crypto.createHash('md5').update(JSON.stringify(s) + srcHash).digest('hex').slice(0, 12);

const out = new Array(slots.length);
const todo = [];
for (const s of slots) {
  if (s.hand) {
    const h = HAND.find(l => l.id === s.hand);
    if (!h) throw new Error('missing hand level ' + s.hand);
    out[s.n - 1] = JSON.parse(JSON.stringify(h));
    continue;
  }
  const file = path.join(CACHE, `L${String(s.n).padStart(3, '0')}.json`);
  const want = keyOf(s);
  if (!force && !only.includes(s.n) && fs.existsSync(file)) {
    const c = JSON.parse(fs.readFileSync(file, 'utf8'));
    if (c.key === want || (only.length && !only.includes(s.n))) { out[s.n - 1] = c.level; continue; }
  }
  todo.push(s);
}

const nWorkers = Math.max(1, Math.min(todo.length, os.cpus().length - 1, 10));
console.log(`${slots.length} levels, ${todo.length} to generate on ${nWorkers} workers (src ${srcHash})`);
const failures = [];
let done = 0;
const t0 = Date.now();
const queue = todo.slice().sort((a, b) => (b.boss ? 1 : 0) - (a.boss ? 1 : 0));

function finish() {
  for (const s of slots) {
    const lv = out[s.n - 1];
    if (!lv) continue;
    Object.assign(lv, { n: s.n, world: s.world, id: lv.id || 'L' + s.n });
    if (s.name) lv.name = s.name;
    if (s.boss) lv.bossLevel = true;
    if (!lv.crayons) lv.crayons = s.crayons;
  }
  const worlds = plan.map((w, i) => ({ name: w.name, paper: w.paper, crayon: w.crayon, intro: w.intro, first: i * 10 + 1 }));
  const missing = out.map((l, i) => l ? null : i + 1).filter(Boolean);
  const body = `/* Crayon Contraptions — 100 levels, generated by tools/gen.js (${new Date().toISOString().slice(0, 10)}).
   Do not edit by hand: change tools/plan.js, tools/archetypes.js or tools/hand.js and regenerate. */
(function (root) {
  const CC = root.CC || (root.CC = {});
  CC.WORLDS = ${JSON.stringify(worlds)};
  CC.LEVELS = ${JSON.stringify(out.filter(Boolean))};
})(typeof window !== 'undefined' ? window : globalThis);
`;
  fs.writeFileSync(path.join(ROOT, 'js', 'levels.js'), body);
  console.log(`wrote js/levels.js: ${out.filter(Boolean).length} levels, ${(Buffer.byteLength(body) / 1024).toFixed(0)} KB, ${((Date.now() - t0) / 1000).toFixed(0)}s`);
  if (missing.length) { console.log('MISSING levels:', missing.join(', ')); for (const f of failures) console.log(`  L${f.n} ${f.arch}: ${JSON.stringify(f.err)}`); process.exitCode = 1; }
}

if (!queue.length) { finish(); return; }
let active = 0;
for (let i = 0; i < nWorkers; i++) {
  const w = new Worker(__filename);
  active++;
  const next = () => { const s = queue.shift(); if (s) w.postMessage(s); else { w.terminate(); if (--active === 0) finish(); } };
  w.on('message', ({ n, res, secs }) => {
    const s = slots[n - 1];
    done++;
    if (res.err) { failures.push({ n, arch: s.arch, err: res.err }); console.log(`[${done}/${todo.length}] L${n} ${s.arch} FAILED ${secs.toFixed(0)}s ${JSON.stringify(res.err).slice(0, 160)}`); }
    else {
      out[n - 1] = res.level;
      fs.writeFileSync(path.join(CACHE, `L${String(n).padStart(3, '0')}.json`), JSON.stringify({ key: keyOf(s), seed: res.seed, rob: res.rob, level: res.level }));
      console.log(`[${done}/${todo.length}] L${n} ${s.arch} ok seed=${res.seed} rob=${res.rob}/6 ink=${res.ink} ${secs.toFixed(0)}s`);
    }
    next();
  });
  w.on('error', e => { console.error('worker error', e); });
  next();
}
